name: "Lint & Release"

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: "install, lint, release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: yarn install
      - run: yarn lint:fix
      - run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
